In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer, LabelEncoder
from sklearn.metrics import *

In [20]:
data = pd.read_csv("Final_Data.csv")

In [21]:
data.drop(columns=["Company_Name", "Unnamed: 0", "Unnamed: 0.1"], inplace=True)

* __For Company_Type__ 
    * __0__ - Startup
    * __1__ - Non-Startup 
* __For Company_Name__ 
    * __0__ - No respose from client
    * __1__ - Client responded 
   

In [45]:
# ax = sb.countplot(x="Contact Status", data=data,  hue="Company_Type")

In [44]:
# plt.figure(figsize=(10,10))
# sb.heatmap(data.corr())

# Seperating Feature and label

In [24]:
X = pd.DataFrame(data.drop(columns="Contact Status"))
y = pd.DataFrame(data["Contact Status"])

# Divide the data into 1:3 ratio

In [25]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Apply Random Forest Algorithm on the data

In [26]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 128, criterion = 'gini', random_state = 55)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=128, n_jobs=1,
            oob_score=False, random_state=55, verbose=0, warm_start=False)

In [27]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [28]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1444,   30],
       [ 160,    2]])

In [29]:
f1_score(y_test, y_pred), accuracy_score(y_test, y_pred)

(0.020618556701030927, 0.8838630806845966)

# Apply SVM Algorithm on the data

In [30]:
# Fitting SVC Classification to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 42)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1471,    3],
       [ 162,    0]])

In [31]:
accuracy_score(y_test, y_pred), f1_score(y_test, y_pred)  

(0.8991442542787286, 0.0)

# Logistic regression

In [32]:
from sklearn.linear_model import LogisticRegression
classify = LogisticRegression(random_state=45)
classify.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1471,    3],
       [ 162,    0]])

In [33]:
accuracy_score(y_test, y_pred), f1_score(y_test, y_pred)  

(0.8991442542787286, 0.0)

# Decision Tree Classification

In [34]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1440,   34],
       [ 160,    2]])

In [35]:
accuracy_score(y_test, y_pred), f1_score(y_test, y_pred)  

(0.8814180929095354, 0.0202020202020202)

# KNN

In [36]:
from sklearn.neighbors import KNeighborsClassifier
classify = KNeighborsClassifier(n_neighbors = 3, metric = "minkowski", p = 2)
classify.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1440,   34],
       [ 160,    2]])

In [37]:
accuracy_score(y_test, y_pred), f1_score(y_test, y_pred)  

(0.8814180929095354, 0.0202020202020202)

# Decision Tree Using Bagging

In [38]:
from sklearn.ensemble import BaggingClassifier
from sklearn import tree
model = BaggingClassifier(tree.DecisionTreeClassifier(random_state=1))
model.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm, model.score(X_test,y_test)

(array([[1440,   34],
        [ 160,    2]]), 0.8765281173594132)

In [39]:
accuracy_score(y_test, y_pred), f1_score(y_test, y_pred)  

(0.8814180929095354, 0.0202020202020202)

# AdaBoost Classifier

In [40]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(random_state=1)
model.fit(X_train, y_train)
model.score(X_test,y_test)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1440,   34],
       [ 160,    2]])

In [41]:
accuracy_score(y_test, y_pred), f1_score(y_test, y_pred), model.score(X_test,y_test)

(0.8814180929095354, 0.0202020202020202, 0.8991442542787286)

# Gradient Boosting Classifier

In [42]:
from sklearn.ensemble import GradientBoostingClassifier
model= GradientBoostingClassifier(learning_rate=0.01,random_state=1)
model.fit(X_train, y_train)
model.score(X_test,y_test)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1440,   34],
       [ 160,    2]])

In [43]:
accuracy_score(y_test, y_pred), f1_score(y_test, y_pred), model.score(X_test,y_test)

(0.8814180929095354, 0.0202020202020202, 0.9009779951100244)